version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.jetbrains.kotlin.jvm
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin.plugin.spring
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: com.squareup.moshi:moshi-adapters
    versions:
    - 1.11.0
  - dependency-name: com.squareup.moshi:moshi-kotlin
    versions:
    - 1.11.0
  - dependency-name: org.junit.jupiter:junit-jupiter-engine
    versions:
    - 5.7.0
  - dependency-name: org.junit.jupiter:junit-jupiter-api
    versions:
    - 5.7.0
  - dependency-name: com.willowtreeapps.assertk:assertk-jvm
    versions:
    - "0.23"
  - dependency-name: info.solidsoft.pitest
    versions:
    - 1.5.2
